// Package layout defines the page layout identifiers shared by the site
// generator (site package) and the build step (build package).
// Keeping them here avoids duplication and ensures both agree on the strings
// written into front-matter and read back during the build.
package layout

// PageLayout identifies the HTML template used to render a content page.
type PageLayout string

func (p PageLayout) String() string { return string(p) }

// Layouts for tree pages generated by the site package.
const (
	PageLayoutPerson          PageLayout = "person"
	PageLayoutPlace           PageLayout = "place"
	PageLayoutSource          PageLayout = "source"
	PageLayoutFamily          PageLayout = "family"
	PageLayoutCitation        PageLayout = "citation"
	PageLayoutListInferences  PageLayout = "listinferences"
	PageLayoutListAnomalies   PageLayout = "listanomalies"
	PageLayoutListTodo        PageLayout = "listtodo"
	PageLayoutListPeople      PageLayout = "listpeople"
	PageLayoutListPlaces      PageLayout = "listplaces"
	PageLayoutListSources     PageLayout = "listsources"
	PageLayoutListSurnames    PageLayout = "listsurnames"
	PageLayoutListChanges     PageLayout = "listchanges"
	PageLayoutListFamilies    PageLayout = "listfamilies"
	PageLayoutListFamilyLines PageLayout = "listfamilylines"
	PageLayoutListTrees       PageLayout = "listtrees"
	PageLayoutCalendar        PageLayout = "calendar"
	PageLayoutTreeOverview    PageLayout = "treeoverview"
	PageLayoutChartAncestors  PageLayout = "chartancestors"
	PageLayoutChartTrees      PageLayout = "charttrees"
)
